[project]
name = "acme"
root = "./"
artifacts_dir = ".makeitso/artifacts"

[manager]
kind = "api:gpt-5-instant"   # or "codex"
approval = "confirm-phase"   # "manual" | "confirm-phase" | "delegate"
budget_tokens = 250000
max_concurrency = 2

[workers.codex]
run_via = "cli"              # "cli" | "api"
profile = "default"
delimiters = { start = "<<MIS:START>>", end = "<<MIS:END>>", json = "<<MIS:JSON>>", err = "<<MIS:ERR>>" }
# Optional execution tuning:
# extra_args = ["-y", "--no-color"]   # flags passed before the goal
# interactive = false                   # inherit stdin/stdout/stderr (true) or capture (false)
# stdin_only = false                    # inherit only stdin; keep stdout/stderr captured
# plain = true                          # request plain output from child (no color/spinner)
# timeout_ms = 15000                    # warn when child is idle for this many ms

[policies]
write_files = "ask"
run_shell = "ask"
network = "ask"

[telemetry]
enabled = true
redact = true
store = "local"

[learning]
mode = "shadow"
regex_repo = "./protocol/regexes.toml"
prompt_repo = "./protocol/prompts/"
replay_dir = ".makeitso/replays"
