/**
 * Core types for makeitso-codex.
 */

export type ApprovalPolicy = "manual" | "confirm-phase" | "delegate";

export type ManagerKind =
  | { kind: "codex" }
  | { kind: "api"; model: string };

/** A planned run of tasks generated by the Manager. */
export interface Plan {
  id: string;
  tasks: Task[];
  budgetTokens: number;
}

/** A single task within a Plan. */
export interface Task {
  id: string;
  goal: string;
  phases: Phase[];
}

/** Phase for a task (bootstrap → task → verify → summarize). */
export interface Phase {
  name: string;
  approval: ApprovalPolicy;
}

/** Run options supplied by the user or config. */
export interface RunOptions {
  manager: ManagerKind;
  policy: ApprovalPolicy;
  budgetTokens: number;
}

/** Delimiter set used by workers to emit machine-parseable logs. */
export interface Delimiters {
  start: string;
  end: string;
  err?: string;
  json?: string;
}
